# Generated by Django 5.1.15 on 2026-06-20 23:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='core.alumni')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('alumni', 'user'), name='unique_verification_per_user')],
            },
        ),
    ]
