"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- Settings that differ between your laptop and the live site ---
# These read from "environment variables" so the live server can use secure
# values without us ever putting secrets in the code. On your laptop the
# defaults kick in, so `python manage.py runserver` keeps working as before.
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECRET_KEY signs cookies/sessions. On the live site, set DJANGO_SECRET_KEY to
# a long random value. Locally, this insecure dev key is fine.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-m$wy2d^+fn=y6o^)e1#w(5-_wde^)()&@f5tx*o10=k_du**q9",
)

# DEBUG shows detailed error pages — handy locally, dangerous in public.
# Defaults to on for local dev; set DJANGO_DEBUG=off on the live site.
DEBUG = os.environ.get("DJANGO_DEBUG", "on").lower() not in ("off", "0", "false")

# Which web addresses are allowed to serve this site. On the live site set
# DJANGO_ALLOWED_HOSTS to your domain, e.g. "tommystapleton.pythonanywhere.com".
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

# For secure (https) form submissions, Django needs to trust your live domain.
# Build https:// origins from the allowed hosts above (skipping local ones).
CSRF_TRUSTED_ORIGINS = [
    f"https://{h}" for h in ALLOWED_HOSTS if h not in ("localhost", "127.0.0.1")
]

# Extra security that only switches on for the live (non-debug) site, where
# everything is served over https. These are no-ops locally over http.
if not DEBUG:
    SECURE_SSL_REDIRECT = True       # force http -> https
    SESSION_COOKIE_SECURE = True     # only send the login cookie over https
    CSRF_COOKIE_SECURE = True        # only send the CSRF cookie over https
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")  # trust the host's https


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  # our app: users, alumni directory, outreach, crowdsourcing
]

# Use our custom user model (adds the is_admin flag and .edu signup).
# This MUST be set before the first migration, which is why we define it up front.
AUTH_USER_MODEL = 'core.User'

# Where @login_required sends anonymous users, and where login/logout land.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'alumni_list'
LOGOUT_REDIRECT_URL = 'login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # project-level templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'  # UW is in Seattle; affects "today"/staleness checks

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Where `python manage.py collectstatic` gathers files for the live server to
# serve. (PythonAnywhere points its "static files" mapping at this folder.)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
